In [1]:
import pandas as pd
from nba_api.stats.endpoints import teamgamelog
import time
import random
from team_games import get_team_log

/Users/bormilan/Documents/GitHub/nba/team_games.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_stats.loc[len(train_stats), ['W', 'L', 'W_PCT']] = 0, 0, 0

In [2]:
df = pd.read_csv('league_games.csv')
df.head()

,Unnamed: 0,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,DREB_2,REB_2,AST_2,STL_2,BLK_2,TOV_2,PF_2,PTS_2,PLUS_MINUS_2,VIDEO_AVAILABLE_2
0,0,22022,1610612755,PHI,Philadelphia 76ers,22200001,2022-10-18,PHI @ BOS,A,240,...,30,36,24,8,3,11,24,126,9,1
1,1,22022,1610612744,GSW,Golden State Warriors,22200002,2022-10-18,GSW vs. LAL,H,240,...,39,48,23,12,4,22,18,109,-14,1
2,2,22022,1610612745,HOU,Houston Rockets,22200005,2022-10-19,HOU @ ATL,A,240,...,32,43,27,10,1,20,21,123,21,1
3,3,22022,1610612751,BKN,Brooklyn Nets,22200006,2022-10-19,BKN vs. NOP,A,240,...,39,53,21,5,10,17,19,114,7,1
4,4,22022,1610612754,IND,Indiana Pacers,22200004,2022-10-19,IND vs. WAS,A,240,...,37,41,27,8,5,16,25,108,-7,1

In [3]:
df_filtered = df[['SEASON_ID', 'GAME_ID', 'GAME_DATE', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ID_2', 'TEAM_NAME_2']]

In [4]:
df_filtered.head()

,SEASON_ID,GAME_ID,GAME_DATE,TEAM_ID,TEAM_NAME,TEAM_ID_2,TEAM_NAME_2
0,22022,22200001,2022-10-18,1610612755,Philadelphia 76ers,1610612738,Boston Celtics
1,22022,22200002,2022-10-18,1610612744,Golden State Warriors,1610612747,Los Angeles Lakers
2,22022,22200005,2022-10-19,1610612745,Houston Rockets,1610612762,Utah Jazz
3,22022,22200006,2022-10-19,1610612751,Brooklyn Nets,1610612764,Washington Wizards
4,22022,22200004,2022-10-19,1610612754,Indiana Pacers,1610612758,Sacramento Kings

In [9]:
def get_team_WL(row):
    time.sleep(random.uniform(0.5,1))
    df1 = get_team_log(row["TEAM_NAME"])
    df2 = get_team_log(row["TEAM_NAME_2"])
    print(row["TEAM_NAME_2"])
    wl1 = df1.loc[df1['Game_ID'] == ("00" + str(row["GAME_ID"])), ['W', 'L', "W_PCT", "MATCHUP"]].values[0]
    print(df2.loc[df2['Game_ID'] == ("00" + str(row["GAME_ID"])), ['W', 'L', "W_PCT"]].values)
    wl2 = df2.loc[df2['Game_ID'] == ("00" + str(row["GAME_ID"])), ['W', 'L', "W_PCT"]].values[0]
    row["W_H"], row["L_H"], row["W_A"], row["L_A"],row["WPCT_H"], row["WPCT_A"], row["MATCHUP"] = wl1[0], wl2[1], wl2[0], wl2[1], wl1[2], wl2[2], wl1[3]
    return row

In [10]:
df_added = df_filtered.apply(get_team_WL, axis=1)

[[0. 0. 0.]]
[[0. 0. 0.]]
[]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
df_added

,SEASON_ID,GAME_ID,GAME_DATE,TEAM_ID,TEAM_NAME,TEAM_ID_2,TEAM_NAME_2,W_H,L_H,W_A,L_A,WPCT_H,WPCT_A,MATCHUP
0,22022,22200002,2022-10-18,1610612747,Los Angeles Lakers,1610612744,Golden State Warriors,0.0,0.0,0.0,0.0,0.000,0.000,GSW
1,22022,22200001,2022-10-18,1610612755,Philadelphia 76ers,1610612738,Boston Celtics,0.0,0.0,0.0,0.0,0.000,0.000,BOS
2,22022,22200012,2022-10-19,1610612762,Utah Jazz,1610612743,Denver Nuggets,0.0,0.0,0.0,0.0,0.000,0.000,DEN
3,22022,22200013,2022-10-19,1610612756,Phoenix Suns,1610612742,Dallas Mavericks,0.0,0.0,0.0,0.0,0.000,0.000,DAL
4,22022,22200014,2022-10-19,1610612758,Sacramento Kings,1610612757,Portland Trail Blazers,0.0,0.0,0.0,0.0,0.000,0.000,POR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,22022,22200179,2022-11-11,1610612761,Toronto Raptors,1610612760,Oklahoma City Thunder,7.0,7.0,4.0,7.0,0.583,0.364,OKC
179,22022,22200180,2022-11-11,1610612759,San Antonio Spurs,1610612749,Milwaukee Bucks,5.0,1.0,10.0,1.0,0.417,0.909,MIL
180,22022,22200181,2022-11-11,1610612763,Memphis Grizzlies,1610612750,Minnesota Timberwolves,8.0,7.0,5.0,7.0,0.667,0.417,MIN
181,22022,22200183,2022-11-11,1610612758,Sacramento Kings,1610612747,Los Angeles Lakers,4.0,9.0,2.0,9.0,0.400,0.182,LAL
182,22022,22200182,2022-11-11,1610612744,Golden State Warriors,1610612739,Cleveland Cavaliers,4.0,3.0,8.0,3.0,0.364,0.727,CLE