In [1]:
import pandas as pd
from nba_api.stats.endpoints import teamgamelog
import time
import random
from team_games import get_team_log
from nba_api.stats.endpoints import boxscoreadvancedv2
from team_games import get_team_lineup

In [2]:
df = pd.read_csv('league_games.csv')
df.head()

,Unnamed: 0,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,DREB_2,REB_2,AST_2,STL_2,BLK_2,TOV_2,PF_2,PTS_2,PLUS_MINUS_2,VIDEO_AVAILABLE_2
0,0,22022,1610612747,LAL,Los Angeles Lakers,22200002,2022-10-18,LAL @ GSW,A,240,...,37,48,31,11,4,18,23,123,14,1
1,1,22022,1610612738,BOS,Boston Celtics,22200001,2022-10-18,BOS vs. PHI,H,240,...,27,31,16,8,3,14,25,117,-9,1
2,2,22022,1610612743,DEN,Denver Nuggets,22200012,2022-10-19,DEN @ UTA,A,240,...,32,43,27,10,1,20,21,123,21,1
3,3,22022,1610612756,PHX,Phoenix Suns,22200013,2022-10-19,PHX vs. DAL,H,240,...,35,40,17,6,4,12,22,105,-2,1
4,4,22022,1610612758,SAC,Sacramento Kings,22200014,2022-10-19,SAC vs. POR,A,240,...,33,44,20,11,2,11,17,115,7,1

In [3]:
df_filtered = df[['SEASON_ID', 'GAME_ID', 'GAME_DATE', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ID_2', 'TEAM_NAME_2']]

In [4]:
df_filtered.head()

,SEASON_ID,GAME_ID,GAME_DATE,TEAM_ID,TEAM_NAME,TEAM_ID_2,TEAM_NAME_2
0,22022,22200002,2022-10-18,1610612747,Los Angeles Lakers,1610612744,Golden State Warriors
1,22022,22200001,2022-10-18,1610612755,Philadelphia 76ers,1610612738,Boston Celtics
2,22022,22200012,2022-10-19,1610612762,Utah Jazz,1610612743,Denver Nuggets
3,22022,22200013,2022-10-19,1610612756,Phoenix Suns,1610612742,Dallas Mavericks
4,22022,22200014,2022-10-19,1610612758,Sacramento Kings,1610612757,Portland Trail Blazers

In [6]:
def get_team_WL(row):
    time.sleep(random.uniform(0.5,1))
    df1 = get_team_log(row["TEAM_NAME"])
    df2 = get_team_log(row["TEAM_NAME_2"])
    print(("00" + str(row["GAME_ID"])))
    wl1 = df1.loc[df1['Game_ID'] == ("00" + str(row["GAME_ID"])), ['W', 'L', "W_PCT", "MATCHUP"]].values[0]
    wl2 = df2.loc[df2['Game_ID'] == ("00" + str(row["GAME_ID"])), ['W', 'L', "W_PCT"]].values[0]
    row["W_H"], row["L_H"], row["W_A"], row["L_A"],row["WPCT_H"], row["WPCT_A"], row["MATCHUP"] = wl1[0], wl2[1], wl2[0], wl2[1], wl1[2], wl2[2], wl1[3]
    print(type(row))
    return row

In [7]:
df_added = df_filtered.apply(get_team_WL, axis=1)

0022200001
<class 'pandas.core.series.Series'>

KeyboardInterrupt:

In [ ]:
df_added

,SEASON_ID,GAME_ID,GAME_DATE,TEAM_ID,TEAM_NAME,TEAM_ID_2,TEAM_NAME_2,W_H,L_H,W_A,L_A,WPCT_H,WPCT_A,MATCHUP
0,22022,22200002,2022-10-18,1610612747,Los Angeles Lakers,1610612744,Golden State Warriors,0.0,0.0,0.0,0.0,0.000,0.000,GSW
1,22022,22200001,2022-10-18,1610612755,Philadelphia 76ers,1610612738,Boston Celtics,0.0,0.0,0.0,0.0,0.000,0.000,BOS
2,22022,22200012,2022-10-19,1610612762,Utah Jazz,1610612743,Denver Nuggets,0.0,0.0,0.0,0.0,0.000,0.000,DEN
3,22022,22200013,2022-10-19,1610612756,Phoenix Suns,1610612742,Dallas Mavericks,0.0,0.0,0.0,0.0,0.000,0.000,DAL
4,22022,22200014,2022-10-19,1610612758,Sacramento Kings,1610612757,Portland Trail Blazers,0.0,0.0,0.0,0.0,0.000,0.000,POR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,22022,22200179,2022-11-11,1610612761,Toronto Raptors,1610612760,Oklahoma City Thunder,7.0,7.0,4.0,7.0,0.583,0.364,OKC
179,22022,22200180,2022-11-11,1610612759,San Antonio Spurs,1610612749,Milwaukee Bucks,5.0,1.0,10.0,1.0,0.417,0.909,MIL
180,22022,22200181,2022-11-11,1610612763,Memphis Grizzlies,1610612750,Minnesota Timberwolves,8.0,7.0,5.0,7.0,0.667,0.417,MIN
181,22022,22200183,2022-11-11,1610612758,Sacramento Kings,1610612747,Los Angeles Lakers,4.0,9.0,2.0,9.0,0.400,0.182,LAL
182,22022,22200182,2022-11-11,1610612744,Golden State Warriors,1610612739,Cleveland Cavaliers,4.0,3.0,8.0,3.0,0.364,0.727,CLE

In [8]:
test = pd.DataFrame(boxscoreadvancedv2.BoxScoreAdvancedV2("0022200002").get_normalized_dict()["PlayerStats"])
test

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0022200002,1610612747,LAL,Los Angeles,1629022,Lonnie Walker IV,Lonnie,F,,29:17,...,13.3,0.286,0.317,0.125,0.125,115.82,113.92,94.93,70,0.044
1,0022200002,1610612747,LAL,Los Angeles,2544,LeBron James,LeBron,F,,35:12,...,12.5,0.519,0.558,0.327,0.327,118.06,115.91,96.59,85,0.195
2,0022200002,1610612747,LAL,Los Angeles,203076,Anthony Davis,Anthony,C,,35:36,...,10.3,0.455,0.520,0.296,0.298,120.49,117.98,98.31,87,0.104
3,0022200002,1610612747,LAL,Los Angeles,201566,Russell Westbrook,Russell,G,,30:41,...,19.0,0.625,0.669,0.214,0.217,121.46,118.89,99.08,75,0.161
4,0022200002,1610612747,LAL,Los Angeles,201976,Patrick Beverley,Patrick,G,,24:40,...,12.5,0.300,0.300,0.102,0.104,107.73,108.00,90.00,55,0.015
5,0022200002,1610612747,LAL,Los Angeles,1630559,Austin Reaves,Austin,,,16:00,...,0.0,0.333,0.436,0.068,0.068,125.76,120.00,100.00,40,0.019
6,0022200002,1610612747,LAL,Los Angeles,1629134,Kendrick Nunn,Kendrick,,,23:03,...,21.4,0.722,0.722,0.188,0.193,122.86,119.74,99.78,56,0.085
7,0022200002,1610612747,LAL,Los Angeles,1629308,Juan Toscano-Anderson,Juan,,,14:18,...,40.0,0.000,0.000,0.132,0.138,118.69,115.80,96.50,34,-0.077
8,0022200002,1610612747,LAL,Los Angeles,1629117,Wenyen Gabriel,Wenyen,,,7:48,...,0.0,0.000,0.000,0.095,0.101,109.29,113.85,94.87,18,-0.438
9,0022200002,1610612747,LAL,Los Angeles,1630346,Matt Ryan,Matt,,,17:49,...,20.0,0.375,0.375,0.111,0.110,111.86,111.81,93.17,41,-0.017
10,0022200002,1610612747,LAL,Los Angeles,1631306,Cole Swider,Cole,,,1:52,...,0.0,0.000,0.000,0.250,0.266,86.91,102.86,85.71,4,0.200
11,0022200002,1610612747,LAL,Los Angeles,1630590,Scotty Pippen Jr.,Scotty,,,1:52,...,0.0,0.000,1.136,0.250,0.266,86.91,102.86,85.71,4,0.400
12,0022200002,1610612747,LAL,Los Angeles,1631108,Max Christie,Max,,,1:52,...,0.0,1.500,1.500,0.250,0.266,86.91,102.86,85.71,4,0.800
13,0022200002,1610612747,LAL,Los Angeles,1627745,Damian Jones,Damian,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
14,0022200002,1610612744,GSW,Golden State,203952,Andrew Wiggins,Andrew,F,,29:28,...,5.3,0.714,0.714,0.190,0.189,121.69,118.92,99.10,73,0.115
15,0022200002,1610612744,GSW,Golden State,203110,Draymond Green,Draymond,F,,24:41,...,9.1,0.400,0.400,0.090,0.092,118.51,116.68,97.23,60,0.082
16,0022200002,1610612744,GSW,Golden State,1626172,Kevon Looney,Kevon,C,,21:08,...,0.0,0.750,0.788,0.070,0.071,117.37,119.23,99.36,53,0.098
17,0022200002,1610612744,GSW,Golden State,202691,Klay Thompson,Klay,G,,19:39,...,10.0,0.538,0.592,0.327,0.329,115.10,112.37,93.64,46,0.122
18,0022200002,1610612744,GSW,Golden State,201939,Stephen Curry,Stephen,G,,32:48,...,11.1,0.545,0.636,0.315,0.324,121.98,118.52,98.77,82,0.194
19,0022200002,1610612744,GSW,Golden State,1629673,Jordan Poole,Jordan,,,28:11,...,14.8,0.333,0.378,0.247,0.257,119.70,114.11,95.09,68,0.071
20,0022200002,1610612744,GSW,Golden State,1630164,James Wiseman,James,,,16:31,...,0.0,0.667,0.515,0.170,0.188,116.13,111.89,93.24,39,0.215
21,0022200002,1610612744,GSW,Golden State,203210,JaMychal Green,JaMychal,,,23:26,...,0.0,0.667,0.667,0.087,0.091,115.20,113.68,94.74,56,0.117
22,0022200002,1610612744,GSW,Golden State,1630228,Jonathan Kuminga,Jonathan,,,13:04,...,40.0,0.000,0.000,0.147,0.158,111.55,108.40,90.33,29,-0.250
23,0022200002,1610612744,GSW,Golden State,1628978,Donte DiVincenzo,Donte,,,21:37,...,30.8,0.583,0.581,0.190,0.200,110.45,109.92,91.60,51,0.037
24,0022200002,1610612744,GSW,Golden State,1630541,Moses Moody,Moses,,,7:35,...,0.0,0.625,0.625,0.211,0.231,111.02,110.77,92.31,18,0.129
25,0022200002,1610612744,GSW,Golden State,1631157,Ryan Rollins,Ryan,,,1:52,...,0.0,0.000,0.000,0.250,0.333,86.91,102.86,85.71,4,-0.200
26,0022200002,1610612744,GSW,Golden State,1631116,Patrick Baldwin Jr.,Patrick,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [9]:
test.columns

Index(['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID',
       'PLAYER_NAME', 'NICKNAME', 'START_POSITION', 'COMMENT', 'MIN',
       'E_OFF_RATING', 'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING',
       'E_NET_RATING', 'NET_RATING', 'AST_PCT', 'AST_TOV', 'AST_RATIO',
       'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT',
       'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE'],
      dtype='object')

In [8]:
boxscoreadvancedv2.BoxScoreAdvancedV2("0022200002").get_normalized_dict().keys()

dict_keys(['PlayerStats', 'TeamStats'])

In [13]:
df_filtered.apply(get_team_lineup, axis=1)

KeyboardInterrupt:

In [4]:
row = get_team_lineup(df_filtered.iloc[0])
row

get_team_linup: 0022200002
SEASON_ID                 22022
GAME_ID                22200002
GAME_DATE            2022-10-18
TEAM_ID              1610612747
TEAM_NAME    Los Angeles Lakers
                    ...
21
22                      1631157
23
24                      1631116
25
Name: 0, Length: 61, dtype: object

/Users/bormilan/Documents/GitHub/nba/team_games.py:91: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  row = row.append(lineup)

SEASON_ID                 22022
GAME_ID                22200002
GAME_DATE            2022-10-18
TEAM_ID              1610612747
TEAM_NAME    Los Angeles Lakers
                    ...
21
22                      1631157
23
24                      1631116
25
Name: 0, Length: 61, dtype: object

,player_id_0,start_position_0,player_id_1,start_position_1,player_id_2,start_position_2,player_id_3,start_position_3,player_id_4,start_position_4,...,player_id_22,start_position_22,player_id_23,start_position_23,player_id_24,start_position_24,player_id_25,start_position_25,player_id_26,start_position_26
0,1629022,F,2544,F,203076,C,201566,G,201976,G,...,1630228,,1628978,,1630541,,1631157,,1631116,

In [11]:
id = df_filtered.iloc[:1]["GAME_ID"]
len(str(id))
# f"00{id}"

41